# -*- coding: utf-8 -*-
"""Resampling & Data Cleaning Weather Data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BdiVePR3fUKLaMh80ULrLnRopLCkyXFv
"""

pip install xlsxwriter

import pandas as pd

aws_12 = pd.read_csv('data_aws_1-2.csv', sep = ";")
aws_38 = pd.read_csv('data_aws_3-8.csv', sep = ";")
aws_915 = pd.read_csv('data_aws_9-15.csv', sep = ";")
aws_1622 = pd.read_csv('data_aws_16-22.csv', sep = ";")
aws_2331 = pd.read_csv('data_aws_23-31.csv', sep = ";")

aws_12.head()

aws_38.head()

aws_915.head()

aws_1622.head()

aws_2331.head()

dfs = [aws_12, aws_38, aws_915, aws_1622, aws_2331]
proses_dfs_jam = []
proses_dfs_hari = []

for df in dfs :
  df['waktu'] = pd.to_datetime(df['waktu'], format = '%d/%m/%Y %H:%M:%S')
  df.set_index('waktu', inplace = True)
  numeric_columns = ['windspeed', 'temp', 'pressure', 'rain', 'solrad', 'watertemp', 'waterlevel']
  for col in numeric_columns:
    df[col] = pd.to_numeric(df[col].str.replace(",", "."), errors='coerce')
  df_jam = df.resample('h').mean()
  df_hari = df.resample('d').mean()
  proses_dfs_jam.append(df_jam)
  proses_dfs_hari.append(df_hari)

for df_jam in proses_dfs_jam :
  print(df_jam.head(), "\n")

for df_hari in proses_dfs_hari :
  print(df_hari.head(), "\n")

data_aws_jam = pd.concat(proses_dfs_jam)
data_aws_jam.sort_index(inplace = True)
data_aws_jam.drop(columns = ['pressure', 'solrad', 'netrad', 'watertemp', 'waterlevel', 'ta_min', 'ta_max', 'pancilevel', 'pancitemp'], inplace = True)
print(data_aws_jam.head(), "\n")

data_aws_hari = pd.concat(proses_dfs_hari)
data_aws_hari.sort_index(inplace = True)
data_aws_hari.drop(columns = ['pressure', 'solrad', 'netrad', 'watertemp', 'waterlevel', 'ta_min', 'ta_max', 'pancilevel', 'pancitemp'], inplace = True)
print(data_aws_hari.head(), "\n")

with pd.ExcelWriter('data_aws_januari_2022.xlsx', engine='xlsxwriter') as writer:
    data_aws_jam.to_excel(writer, sheet_name='Per Jam', index=True)
    data_aws_hari.to_excel(writer, sheet_name='Per Hari', index=True)